package:
  name: pypy-with-meta
  version: 3.5

outputs:
  # normal python build process for this output - fill in your recipe for this output
  - name: python
    build: blah
    requirements:
      run:
        - _python_impl 1.0 pypy
  # mutex package to keep only one python implementation in a given env
  - name: _python_impl
    version: 1.0
    build:
      string: pypy
      # track_features doesn't really track anything anymore (blas metapackage
      # dependencies do the same job better). This is still here, though, as it
      # effectively "weighs down" nomkl packages, allowing mkl to take
      # precedence when defaults is the top channel priority.
      track_features:
        - python_impl_pypy
